import React, { useEffect, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { getConceptExplanation, getConceptImage } from '../services/geminiService';
import { Loader } from './Loader';

interface VisualizerProps {
  topic: string;
}

export const Visualizer: React.FC<VisualizerProps> = ({ topic }) => {
  const [state, setState] = useState<{
    explanation: string | null;
    imageUrl: string | null;
    loading: boolean;
    error: string | null;
  }>({
    explanation: null,
    imageUrl: null,
    loading: true,
    error: null,
  });

  useEffect(() => {
    let isMounted = true;

    const fetchData = async () => {
      setState(prev => ({ ...prev, loading: true, error: null }));
      
      try {
        // Run parallel requests for speed
        const [explanationText, imageBase64] = await Promise.all([
          getConceptExplanation(topic),
          getConceptImage(topic)
        ]);

        if (isMounted) {
          setState({
            explanation: explanationText,
            imageUrl: imageBase64 || null,
            loading: false,
            error: null,
          });
        }
      } catch (err) {
        if (isMounted) {
          setState(prev => ({ 
            ...prev, 
            loading: false, 
            error: "Failed to load concept data. Please try again." 
          }));
        }
      }
    };

    fetchData();

    return () => {
      isMounted = false;
    };
  }, [topic]);

  if (state.loading) {
    return <Loader message={`Analyzing ${topic} and generating visuals...`} />;
  }

  if (state.error) {
    return (
      <div className="p-8 text-center text-red-500 bg-red-50 rounded-xl">
        <p>{state.error}</p>
      </div>
    );
  }

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 animate-fade-in">
      {/* Text Content */}
      <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200 overflow-y-auto max-h-[600px] prose prose-slate prose-indigo">
        <ReactMarkdown>{state.explanation || ""}</ReactMarkdown>
      </div>

      {/* Visual Content */}
      <div className="flex flex-col gap-4">
        <div className="bg-white p-4 rounded-2xl shadow-sm border border-slate-200">
          <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-3">AI Visualization</h3>
          <div className="relative w-full aspect-video bg-slate-100 rounded-xl overflow-hidden flex items-center justify-center group">
             {state.imageUrl ? (
               <img 
                 src={state.imageUrl} 
                 alt={`AI visualization of ${topic}`}
                 className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
               />
             ) : (
               <div className="text-slate-400 text-sm p-4 text-center">
                 Visualization could not be generated for this specific topic.
               </div>
             )}
          </div>
          <p className="mt-3 text-xs text-slate-400 text-center">
            Generated by Gemini 2.5 Flash Image
          </p>
        </div>
      </div>
    </div>
  );
};